export const SET_GUIDE_STATUS = 'SET_GUIDE_STATUS'
export const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS'
export const SET_APP_NAV_SHOW = 'SET_APP_NAV_SHOW'
export const ADD_TO_CART = 'ADD_TO_CART'
export const GET_GOODS = 'GET_GOODS'
export const GET_THE_GOODS = 'GET_THE_GOODS'
export const SORT_GOODS = 'SORT_GOODS'
